### ISSUE TITLE
768x512 model

### ISSUE THREAD

**Issue by osfa** [skyflynil/stylegan2#11]
Thanks for some nice improvements!

In the readme there are some outputs for what seems to be wikiart portraits in 768x512. any chance of accessing that model for some transfer learning? 
thanks!

**Comment by xivh** [comment]
I am training a network in 768x512 config-e - are you still looking for one?

**Comment by osfa** [comment]
@xivh yes!! much obliged!

**Comment by xivh** [comment]
@osfa Sorry for the wait, I used a university computing cluster and I'm checking to make sure it's ok to release it.

**Comment by xivh** [comment]
@osfa 

https://archive.org/details/network-snapshot-004223

It is config-e 768 height 512 width, and you'll have to fix what I mentioned in #13 because I used res-log2 = 8 (so it's 3 by 2).

**Comment by osfa** [comment]
@xivh thank you so much for doing this for a stranger online!
