### ISSUE TITLE
Different batch size for 640x640 dataset

### ISSUE THREAD

**Issue by Br1lopez** [skyflynil/stylegan2#17]
Hello, I have been trying to train with my custom dataset (48k, 640x640) and the follwing error appears:

"Cannot batch tensors with different shapes in component 0. First element had shape [3,640,640] and element 1 had shape [1,640,640]"

I have used  "--min-h=5 --min-w=5 --res-log2=7".

That first mismatching number is the batch size, isn't it? How could I solve this?

Thanks in advance!

**Comment by dvschultz** [comment]
first number is channels. this indicates you have a grayscale image amongst some RGB images.
